@MovieAPI_HostAddress = http://localhost:5092

### Get all Spider-Man movies
GET {{MovieAPI_HostAddress}}/api/movies
Accept: application/json

###

### Get movie by IMDb ID
GET {{MovieAPI_HostAddress}}/api/movies/tt0145487
Accept: application/json

###